LBC/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from app import views as app_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'LBC.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'app/login.html'}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,  {'next_page': '/app/rummage_list/'}, name='logout'),
    url(r'^accounts/register/$', app_views.register, name='register'),
    url(r'^accounts/register_success/$', app_views.register_success, name='register_success'),    
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^app/', include('app.urls', namespace="app")),
    url(r'^$', app_views.home, name='index'),
]

app/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import app.views

app_name = 'app'

urlpatterns = [
    url(r'^$', app.views.home, name='index'),
    url(r'^accueil/$', app.views.home, name='home'),
    url(r'^article/(?P<article_id>\d+)/$', app.views.article_view, name='article_view'),
    url(r'^articles/(?P<year>\d{4})/(?P<month>\d{2})/$', app.views.home, name='article_list'),
    
    url(r'^rummage/(?P<rummage_id>\d+)/$', app.views.rummage, name='rummage'),
    url(r'^rummage_list/$', app.views.rummage_list, name='rummage_list'),
    url(r'^rummage_add/$', app.views.rummage_add, name='rummage_add'),
    url(r'^rummage_delete/(?P<rummage_id>\d+)/$', app.views.rummage_delete, name='rummage_delete'),
    url(r'^rummage_update/(?P<rummage_id>\d+)/$', app.views.rummage_update, name='rummage_update'),
    
    url(r'^criteria/(?P<criteria_id>\d+)/$', app.views.criteria, name='criteria'),
    url(r'^criteria_list/(?P<rummage_id>\d+)/$', app.views.criteria_list, name='criteria_list'),
    url(r'^criteria_add/(?P<rummage_id>\d+)/$', app.views.criteria_add, name='criteria_add'),
    url(r'^criteria_delete/(?P<criteria_id>\d+)/$', app.views.criteria_delete, name='criteria_delete'),
    url(r'^criteria_update/(?P<criteria_id>\d+)/$', app.views.criteria_update, name='criteria_update'),
    
    url(r'^rummage_item/(?P<rummageItemId>\d+)/$', app.views.rummage_item, name='rummage_item'),
    url(r'^rummage_item_list/(?P<rummage_id>\d+)/$', app.views.rummage_item_list, name='rummage_item_list'),
    url(r'^rummage_item_add/(?P<rummage_id>\d+)/$', app.views.rummage_item_add, name='rummage_item_add'),
    url(r'^rummage_item_delete/(?P<rummageItemId>\d+)/$', app.views.rummage_item_delete, name='rummage_item_delete'),
    url(r'^rummage_item_update/(?P<rummage_item_id>\d+)/$', app.views.rummage_item_update, name='rummage_item_update'),
    
    url(r'^note_add/(?P<rummageItemId>\d+)/$', app.views.note_add, name='note_add'),
    
    
    url(r'^redirection/$', app.views.redirection_view, name='redirection'),
    url(r'^template/$', app.views.tpl, name='template'),
    
]

#Debug
urlpatterns += staticfiles_urlpatterns()

app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
	<head>
		<title>{% block title %}Mon app sur les petites annonces en ligne{% endblock %}</title>
	    <!-- Bootstrap -->
	    <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet">
	    <!-- Bootstrap theme -->
	    <link href="{% static 'app/css/bootstrap-theme.min.css' %}" rel="stylesheet">
	    <!-- Custom styles for this template -->
	    <link href="{% static 'app/css/jquery-ui.min.css' %}" rel="stylesheet">
	    <link href="{% static 'app/css/jquery-ui.structure.min.css' %}" rel="stylesheet">
	    <link href="{% static 'app/css/jquery-ui.theme.min.css' %}" rel="stylesheet">
		<link href="{% static 'app/css/theme.css' %}" rel="stylesheet" />
	</head>
	
  <body role="document">

	    <!-- Fixed navbar -->
		{% block nav %}
		    <nav class="navbar navbar-inverse navbar-fixed-top">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#">LBC - aide à la décision</a>
					</div>
					<div id="navbar" class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
							<li><a href="/blog">Blog</a></li>
							<li><a href="{% url 'app:rummage_list' %}" class="active">Application</a></li>
							<li>
								{% if user.is_authenticated %}
									<a href="{% url 'logout' %}">Déconnexion</a>
								{% else %}
									<a href="{% url 'login' %}">Connexion</a>
								{% endif %}
							</li>
							<!-- <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
							<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li class="dropdown-header">Nav header</li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
							</ul>
							</li> -->
							<li><a href="/contact/">Contact</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
			</nav>
		{% endblock %}


		<header>Le bon coin - aide à la décision</header>

		{% for msg in errors %}
			{% for type, message in msg %}
				<div class="alert {{type}}" role="alert">
					<strong>{{ message|escape }}</strong>
				</div>
			{% endfor %}
		{% empty %}
		{% endfor %}
		<div class="container theme-showcase" role="main">
			{% block content %}{% endblock %}
		</div>
		<footer>Copyright Kikoolol</footer>		
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'app/js/jquery-2.1.4.js' %}"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static 'app/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'app/js/jquery-ui.min.js' %}"></script>
		<!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
			<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script> -->
  			
		{% block custom_scripts %}{% endblock %}
	</body>
</html>

app/templates/app/criteria.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}{{ rummage.title }}{% endblock %}

{% block content %}

		<div class="rummage">
			<h3><a href="{{ rummage.url }}">{{ rummage.title }}</a></h3>
			<h4>Requête</h4>
			<ul>
				{% if query.category %}
					<li>Catégorie : {{ query.category }}</li>
				{% endif %}
				{% if query.region %}
					<li>Région : {{ query.region }}</li>
				{% endif %}
				{% if query.city %}
					<li>Ville : {{ query.city }}</li>
				{% endif %}
				{% if query.text %}
					<li>Recherche : {{ query.text }}</li>
				{% endif %}
			</ul>
			<h4>Critères</h4>
			<p>
				<ul>
					{% for criteria in criterias %}
						<li>{{ criteria.name }} : {{ criteria.weight }}</li>
					{% empty %}
						<li>Aucun critères définis pour cette recherche actuellement.</li>
					{% endfor %}
					<li><a href="{% url 'app:criteria' %}">Ajouter un critère d'évaluation</a></li>
					
				</ul>
			</p>
			<h4>Annonces sauvegardées:</h4>
			<p></p>
			<h4>Annonces disponibles:</h4>
			<p></p>
		</div>


{% endblock %}

<!-- 
regex : 
www\.leboncoin\.fr\/([\w\_]+)\/offres\/([\w\_]+)\/[\w\_\/]*\?th=([\d]+)&q=([\w\d%\.\-]+)

https://www.leboncoin.fr/instruments_de_musique/offres/ile_de_france/paris/?th=1&q=zoom%20R8 

urlparse('https://www.leboncoin.fr/instruments_de_musique/offres/ile_de_france/paris/?th=1&q=zoom%20R8')

ParseResult(scheme='https', netloc='www.leboncoin.fr', path='/instruments_de_musique/offres/ile_de_france/paris/', params='', query='th=1&q=zoom%20R8', fragment='')

-->

app/templates/app/criteria_add.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}Ajouter un critère{% endblock %}

{% block content %}

	<div class="jumbotron">
		<h1>Ajouter un critère</h1>
		<p>Vous pouvez ajouter un critère à une recherche afin de vous aider à évaluer celle-ci en fonction de vos besoins.</p>
	</div>

	<div class="page-header">
		<div class="row">
			<div class="col-md-12">
					<a href="{% url 'app:rummage' rummage.id %}"><h1>{{ rummage.title }}</h1></a>
			</div>
		</div> 
	</div>

	<div class="page-header">
		<h1>Nouveau critère</h1>
	</div>

	<div class="row">
    	<div class="col-md-12">
			{% if send %}
				<div class="alert alert-success" role="alert">Votre critère a bien été enregistré.</div>
			{% endif %}			
			<form action="{% url 'app:criteria_add' rummage.id %}" method="post">{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value="Ajouter" />
			</form>
		</div>
	</div>	
	
	<h2>Critères</h2>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-condensed">
				<thead>
				  <tr>
				<th>#</th>
				<th>Critère</th>
				<th>Poids</th>
				<th></th>
				  </tr>
				</thead>
				<tbody>
					{% for criteria in criterias %}
						<tr>
							<td>
								#
							</td>
							<td>
								{{ criteria.name }}
							</td>
							<td>
								{{ criteria.weight }}
							</td>
							<td align="right">
								<a href="{% url 'app:criteria_update' criteria.id %}"><button type="button" class="btn btn-sm btn-default">Éditer</button></a>
								<a href="{% url 'app:criteria_delete' criteria.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>
							</td>
						</tr>
					{% empty %}
						<tr>
							<td>Aucun critère définis pour cette recherche</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>	

{% endblock %}

app/templates/app/criteria_update.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}Modifier un critère{% endblock %}
{% block content %}

	<div class="jumbotron">
		<h1>Modifier un critère</h1>
		<p>Vous pouvez modifier un critère existant - attention, cela peut changer complètement la pertinence des annonces sauvegardées !</p>
	</div>

	<div class="page-header">
		<div class="row">
			<div class="col-md-12">
					<a href="{% url 'app:rummage' rummage.id %}"><h1>{{ rummage.title }}</h1></a>
			</div>
		</div> 
	</div>

	<div class="page-header">
		<h1>Votre critère</h1>
	</div>

	<div class="row">
    	<div class="col-md-12">
			{% if send %}
				<div class="alert alert-success" role="alert">Votre critère a bien été enregistré.</div>
			{% endif %}			
			<form action="{% url 'app:criteria_update' criteria.id %}" method="post">{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value="Enregistrer" />
			</form>
		</div>
	</div>
	
	<h2>Critères</h2>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-condensed">
				<thead>
				  <tr>
				<th>#</th>
				<th>Critère</th>
				<th>Poids</th>
				<th></th>
				  </tr>
				</thead>
				<tbody>
					{% for criteria in criterias %}
						<tr>
							<td>
								#
							</td>
							<td>
								{{ criteria.name }}
							</td>
							<td>
								{{ criteria.weight }}
							</td>
							<td align="right">
								<a href="{% url 'app:criteria_update' criteria.id %}"><button type="button" class="btn btn-sm btn-default">Éditer</button></a>
								<a href="{% url 'app:criteria_delete' criteria.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>
							</td>
						</tr>
					{% empty %}
						<tr>
							<td>Aucun critère définis pour cette recherche</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
		
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}Liste des recherches en cours{% endblock %}

{% block content %}

	<div class="jumbotron">
		<h1>Mes recherches</h1>
		<p>Vous pouvez consulter ici les recherches effectuées sur le bon coin que vous avez sauvegardées dans l'application.</p>
	</div>

	<div class="page-header">
		<h1>Recherches en cours</h1>
	</div>

	<div class="row">
    	<div class="col-md-12">
    		<table class="table table-striped table-condensed">
            <tbody>
				{% for rummage in rummages_list %}
	            	<tr>
	                	<td>
	                		<a href="{% url 'app:rummage' rummage.id %}">{{ rummage.title }}</a>
	                	</td>
	                	<td align="right">
	                		<a href="{% url 'app:rummage_update' rummage.id %}"><button type="button" class="btn btn-sm btn-default">Éditer</button></a>
	                		<a href="{% url 'app:rummage_delete' rummage.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>        
	                	</td>
	            	</tr>
				{% empty %}
	            	<tr>
	                	<td>Aucune recherche en cours. Identifiez-vous pour accéder à vos recherches</td>
	            	</tr>
				{% endfor %}
	            </tbody>
            </table>
    		<a href="{% url 'app:rummage_add' %}"><button type="button" class="btn btn-sm btn-default">Nouvelle recherche</button></a>
    	</div>
    </div>

{% endblock %}

app/templates/app/rummage.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}{{ rummage.title }}{% endblock %}

{% block content %}

	<div class="jumbotron">
		<h1>Recherche</h1>
		<p>Cette page vous présente les détails de la recherche sélectionnée, ainsi que les critères associés et les annonces disponibles ou sauvegardées</p>
	</div>

	<div class="page-header">
		<div class="row">
			<div class="col-md-9">
				<a href="{{ rummage.url }}"><h1>{{ rummage.title }}</h1></a>  			
			</div>
			<div class="rummage-title-actions col-md-3">		
					<a href="{% url 'app:rummage_update' rummage.id %}"><button type="button" class="btn btn-sm btn-default">Éditer</button></a>
					<a href="{% url 'app:rummage_delete' rummage.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>   
			</div>
		</div> 
	</div>

	<div class="rummage-elements">
		<h4>	
			{% if query.category %}
				<span class="label label-default">Catégorie : {{ query.category }}</span>
			{% endif %}
			{% if query.region %}
				<span class="label label-default">Région : {{ query.region }}</span>
			{% endif %}
			{% if query.city %}
				<span class="label label-default">Ville : {{ query.city }}</span>
			{% endif %}
			{% if query.text %}
				<span class="label label-default">Recherche : {{ query.text }}</span>
			{% endif %}			
		</h4>	
	</div>
	
	<h2>Critères</h2>

	<div class="row">
		<div class="col-md-{% if savedAdsList %}6{% else %}12{% endif %}">
			<table class="table table-striped table-condensed">
				<thead>
				  <tr>
					<th>Critère</th>
					<th>Poids</th>
					<th></th>
				  </tr>
				</thead>
				<tbody>
					{% for criteria in criterias %}
						<tr>
							<td>
								{{ criteria.name }}
							</td>
							<td>
								{{ criteria.weight }}
							</td>
							<td align="right">
								<a href="{% url 'app:criteria_update' criteria.id %}"><button type="button" class="btn btn-sm btn-default">Éditer</button></a>
								<a href="{% url 'app:criteria_delete' criteria.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>
							</td>
						</tr>
					{% empty %}
						<tr>
							<td>Aucun critère définis pour cette recherche</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<a href="{% url 'app:criteria_add' rummage.id %}"><button type="button" class="btn btn-sm btn-default">Ajouter un critère d'évaluation</button></a>
		</div>		
		
		{% if savedAdsList %}
			<div class="col-md-6">
				<div id="highcharts_container"></div>
			</div>
		{% endif %}
	</div>

	<h2>Annonces sauvegardées:</h2>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-condensed">
				<tbody>
					{% for ad_id, ad_infos in savedAdsList.items %}
						<tr
							{% if ad_infos.disabled %}
								class="rummage-item-disabled"
							{% elif ad_infos.type == 'pro' %}
								class="rummage-item-pro"
							{% endif %}
						>
							<td>
								<a href="{{ ad_infos.url }}"><img  class="rummage-item-thumbnail" src="{{ ad_infos.thumbnail_url }}" alt="{{ ad_infos.name }} image"></a>
							</td>
							<td>{{ ad_infos.type }}
								<a href="{{ ad_infos.url }}">{{ ad_infos.name }} : {{ ad_infos.price }}&euro;</a>
							</td>
							<td>
								{{ ad_infos.updated_date }}
							</td>
							<td>
								{{ ad_infos.score }}
							</td>
							<td align="right" width="20%">
								<a href="{% url 'app:rummage_item' ad_infos.id %}"><button type="button" class="btn btn-sm btn-default">Noter</button></a>  
								<a href="{% url 'app:rummage_item_delete' ad_infos.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>  
							</td>
						</tr>
					{% empty %}
						<tr>
							<td>Aucune annonce disponible pour cette recherche actuellement.</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	<h2>Annonces disponibles:</h2>

	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-condensed">
				<tbody>
					{% for ad_id, ad_infos in ads_list.items %}
						<tr {% if ad_infos.disabled %}class="rummage-item-disabled"{% elif ad_infos.type == 'pro' %}class="rummage-item-pro"{% endif %}>
						<td>
							<a href="{{ ad_infos.href }}"><img class="rummage-item-thumbnail" src="{{ ad_infos.img_src }}" alt="{{ ad_infos.title }} image"></a>
						</td>
						<td>
							<a href="{{ ad_infos.href }}">{% if ad_infos.type == 'pro' %}PRO - {% endif %}{{ ad_infos.title }} : {{ ad_infos.price }}</a>
						</td>
						<td>
							<!-- {{ ad_infos.title }} TODO display post date -->
						</td>
						<td align="right" width="20%">
							<form action="{% url 'app:rummage_item_add' rummage.id %}" method="POST">{% csrf_token %}
								<input type="hidden" name="selected" value="True">
								<input type="hidden" name="rummage_id" value="{{ rummage.id }}">
								<input type="hidden" name="lbc_id" value="{{ ad_id }}">
								<input type="hidden" name="name" value="{{ ad_infos.title }}">
								<input type="hidden" name="url" value="{{ ad_infos.href }}">
								<input type="hidden" name="thumbnail_url" value="{{ ad_infos.img_src }}">
								<input type="hidden" name="price" value="{{ ad_infos.price }}">
								<input type="hidden" name="infos" value="{{ ad_infos.data_info }}">
								<input type="submit" class="btn btn-sm btn-default" value="Sauvegarder">
							</form>
							<a href="{% url 'app:rummage_item_delete' ad_id %}"><button type="button" class="btn btn-sm btn-danger">Ignorer</button></a>  
						</td>
						</tr>
					{% empty %}
						<tr>
							<td>Aucune annonce disponible pour cette recherche actuellement.</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}
{% block custom_scripts %}

	<script src="{% static 'app/js/highcharts.js' %}"></script>
	<script src="{% static 'app/js/highcharts-more.js' %}"></script>
	<script  type="text/javascript">
		{% if savedAdsList %}
			$( function() {

				$('#highcharts_container').highcharts({

					chart: {
					renderTo: 'highcharts_container',
						polar: true,
						type: 'line',
						margin: 0,
					},

					title: {
						text: '',
						x: -80,
					},

					pane: {
						size: '80%'
					},

					xAxis: {

						categories: [
						{% for criteria in criterias %}
							'{{ criteria.name }}',
						{% empty %}
						{% endfor %}],
						tickmarkPlacement: 'on',
						lineWidth: 0,
						labels: {
							align: 'center',
							distance: 50,
						}
					},

					yAxis: {
						gridLineInterpolation: 'polygon',
						lineWidth: 0,
						min: 0,
						max : 5,
						endOnTick: true,
						showLastLabel: false,
						tickPositions: [0, 1, 2, 3, 4, 5],
					},

					series: [
						{% for ad_id, ad_infos in savedAdsList.items %}
						{
							type: 'area',
							name : '{{ ad_infos.name }}',
							data : [
							{% for criteria in ad_infos.criterias %}
								{{ criteria.note }},
							{% empty %}
							{% endfor %}
							],
							pointPlacement: 'on',
						},
						{% empty %}
						{% endfor %} 
					]

				});

			} );
		{% endif %}
	</script>
{% endblock %}

<!-- 
regex : 
www\.leboncoin\.fr\/([\w\_]+)\/offres\/([\w\_]+)\/[\w\_\/]*\?th=([\d]+)&q=([\w\d%\.\-]+)

https://www.leboncoin.fr/instruments_de_musique/offres/ile_de_france/paris/?th=1&q=zoom%20R8 

urlparse('https://www.leboncoin.fr/instruments_de_musique/offres/ile_de_france/paris/?th=1&q=zoom%20R8')

ParseResult(scheme='https', netloc='www.leboncoin.fr', path='/instruments_de_musique/offres/ile_de_france/paris/', params='', query='th=1&q=zoom%20R8', fragment='')

http://www.jerecuperemonex.com/se-remettre-d-une-rupture/amoureuse-difficile/
http://www.jerecuperemonex.com/rupture-amoureuse/limiter-les-degats-lors-d-une-rupture-amoureuse/


-->

app/templates/app/rummage_item.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}{{ rummage.title }}{% endblock %}

{% block content %}

	<div class="jumbotron">
		<h1>Annonce</h1>
		<p>Cette page vous permet d'évaluer la pertinence d'une annonce sauvegardée, en fonction des critères que vous avez définis.</p>
	</div>

	<div class="page-header">
		<div class="row">
			<div class="col-md-9">
				<a href="{{ rummageItem.url }}"><h1>{{ rummageItem.name }} - {{ rummageItem.price }}</h1></a>  			
			</div>
			<div class="rummage-title-actions col-md-3">		
				<a href="{% url 'app:rummage_item_delete' rummageItem.id %}"><button type="button" class="btn btn-sm btn-danger">Supprimer</button></a>   
			</div>
		</div>
		<div class="row">
			<a href="{% url 'app:rummage' rummage.id %}"><button type="button" class="btn btn-sm btn-default">Liste des annonces</button></a>
		</div> 	
	</div>
	
	<h2>Critères</h2>

	<div class="row">
		<div class="col-md-6">
			<form action="{% url 'app:note_add' rummageItem.id %}" method="POST">
			{% csrf_token %}
				<table class="table table-striped table-condensed">
					<thead>
					 	<tr>
						<th>Poids</th>
						<th colspan="2">Valeur</th>
					  </tr>
					</thead>
					<tbody>
						{% for criteria in criterias %}
							<tr>
								<td width="20%">
									{{ criteria.weight }}
								</td>
								<td width="40%">
									<label for="amount_{{ criteria.id }}">{{ criteria.name }} : </label>
									<span id="label_amount_{{ criteria.id }}" style="border:0; color:#f6931f; font-weight:bold;"></span>
									<input type="text" name="{{ criteria.id }}" id="amount_{{ criteria.id }}" readonly style="border:0; color:#f6931f; font-weight:bold; display:none;" value="{%for criteria_id, criteria_note in notes_list.items %}{% if criteria_id == criteria.id %}{{ criteria_note }}{% endif %}{% empty %}0.0{% endfor %}"> 
								</td>
								<td width="40%">  										
									<div id="slider_{{ criteria.id }}"></div>
								</td>
							</tr>
						{% empty %}
							<tr>
								<td>Aucun critère définis pour cette recherche</td>
							</tr>
						{% endfor %}
						<tr>
							<td colspan="3" align="right">
								<input type="submit" value="Enregistrer">
							</td>
						</tr>
					</tbody>
				</table>
			</form>
			<a href="{% url 'app:criteria_add' rummage.id %}"><button type="button" class="btn btn-sm btn-default">Ajouter un critère d'évaluation</button></a>	
		</div>

		<div class="col-md-6">
			<div id="highcharts_container"></div>
		</div>
	</div>

</div>


{% endblock %}


{% block custom_scripts %}

	<script src="{% static 'app/js/highcharts.js' %}"></script>
	<script src="{% static 'app/js/highcharts-more.js' %}"></script>
	<script  type="text/javascript">
		$( function() {

			{% for criteria in criterias %}

				$( "#slider_{{ criteria.id }}" ).slider({
					value: {{ criteria.note }}, 
					min: 0,
					max: 5,
					step: 0.5,
					slide: function( event, ui ) {
						$( "#amount_{{ criteria.id }}" ).val( ui.value );
						$( "#label_amount_{{ criteria.id }}" ).text( ui.value );
					}
				});
				$( "#amount_{{ criteria.id }}" ).val( $( "#slider_{{ criteria.id }}" ).slider( "value" ) );
				$( "#label_amount_{{ criteria.id }}" ).text( $( "#slider_{{ criteria.id }}" ).slider( "value" ) );


			{% empty %}
			{% endfor %}

			$('#highcharts_container').highcharts({

				chart: {
            		renderTo: 'highcharts_container',
					polar: true,
					type: 'line',
					margin: 0,
				},

				title: {
					text: '',
					x: -80,
				},

				pane: {
					size: '80%'
				},

				xAxis: {

					categories: [
					{% for criteria in criterias %}
						'{{ criteria.name }}',
					{% empty %}
					{% endfor %}],
					tickmarkPlacement: 'on',
					lineWidth: 0,
					labels: {
						align: 'center',
						distance: 50,
					}
				},

				yAxis: {
					gridLineInterpolation: 'polygon',
					lineWidth: 0,
					min: 0,
					max : 5,
					endOnTick: true,
					showLastLabel: false,
					tickPositions: [0, 1, 2, 3, 4, 5],
				},

				series: [{
					type: 'area',
					name: '{{ rummageItem.name }}',
					data: [
					{% for criteria in criterias %}
						{{ criteria.note }},
					{% empty %}
					{% endfor %}],
					pointPlacement: 'on'
				}, ]

			});

		} );

	</script>
{% endblock %}